import { Contract } from "./base/base$Contract";
import { ClaimGroup } from "./baseClaimGroup";
import { Policy } from "./base$Policy";
import { DicRegion } from "./base/base$DicRegion";
import { DicDistrict } from "./base/base$DicDistrict";
import { DicCurrency } from "./base/base$DicCurrency";
import { ClaimStatus, ClaimDecision } from "../enums/enums";
import { OrganizationExt } from "./base$OrganizationExt";
import { ClaimRecipient } from "./insurance_ClaimRecipient";
import { InsurancePayment } from "./claim$InsurancePayment";
import { ClaimAcl } from "./ClaimAcl";
import { ClaimDamage } from "./insurance_ClaimDamage";
import { UserExtend } from "./extend_User";
import { Individual } from "./base/base$Individual";
import { ClaimResponsibleForDamage } from "./insurance_ClaimResponsibleForDamage";
import { ClaimLetterDoc } from "./ClaimLetterDoc";
export class Claim extends Contract {
  static NAME = "baseClaim";
  group?: ClaimGroup | null;
  policy?: Policy | null;
  journalNumber?: number | null;
  journalDate?: any | null;
  eventTime?: any | null;
  eventRegion?: DicRegion | null;
  eventDistrict?: DicDistrict | null;
  eventAddress?: string | null;
  lawRepresentative?: string | null;
  eventCase?: string | null;
  eventExpense?: any | null;
  currency?: DicCurrency | null;
  status?: ClaimStatus | null;
  organization?: OrganizationExt | null;
  claimRecipients?: ClaimRecipient[] | null;
  insurancePayments?: InsurancePayment[] | null;
  claimAcl?: ClaimAcl[] | null;
  damages?: ClaimDamage[] | null;
  claimFundId?: any | null;
  euroProtocol?: boolean | null;
  directSettlement?: boolean | null;
  decision?: ClaimDecision | null;
  reason?: string | null;
  decisionDate?: any | null;
  committeeDecisionFundId?: any | null;
  payoutFundId?: any | null;
  executor?: UserExtend | null;
  returnDescription?: string | null;
  rejectDescription?: string | null;
  reporterReturnDescription?: string | null;
  reporterApproveDescription?: string | null;
  processInstanceId?: any | null;
  insuranceObject?: string | null;
  insuranceValue?: any | null;
  insuranceSum?: any | null;
  driver?: Individual | null;
  franchise?: string | null;
  reasonForPayment?: string | null;
  calculationOfCompensation?: string | null;
  isInsuredEvent?: any | null;
  hasRegress?: boolean | null;
  responsibleForDamage?: ClaimResponsibleForDamage[] | null;
  claimUser?: UserExtend | null;
  letterDocs?: ClaimLetterDoc[] | null;
}
export type ClaimViewName =
  | "_base"
  | "_local"
  | "_minimal"
  | "claim-fund-view"
  | "claim-fund-view"
  | "claim-online-view"
  | "claim-online-view"
  | "claim-report-view"
  | "claim-report-view";
export type ClaimView<V extends ClaimViewName> = V extends "_base"
  ? Pick<
      Claim,
      | "id"
      | "contractNumber"
      | "journalNumber"
      | "journalDate"
      | "eventTime"
      | "eventAddress"
      | "lawRepresentative"
      | "eventCase"
      | "eventExpense"
      | "status"
      | "claimFundId"
      | "euroProtocol"
      | "directSettlement"
      | "decision"
      | "reason"
      | "decisionDate"
      | "committeeDecisionFundId"
      | "payoutFundId"
      | "returnDescription"
      | "rejectDescription"
      | "reporterReturnDescription"
      | "reporterApproveDescription"
      | "processInstanceId"
      | "insuranceObject"
      | "insuranceValue"
      | "insuranceSum"
      | "franchise"
      | "reasonForPayment"
      | "calculationOfCompensation"
      | "isInsuredEvent"
      | "hasRegress"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
    >
  : V extends "_local"
  ? Pick<
      Claim,
      | "id"
      | "journalNumber"
      | "journalDate"
      | "eventTime"
      | "eventAddress"
      | "lawRepresentative"
      | "eventCase"
      | "eventExpense"
      | "status"
      | "claimFundId"
      | "euroProtocol"
      | "directSettlement"
      | "decision"
      | "reason"
      | "decisionDate"
      | "committeeDecisionFundId"
      | "payoutFundId"
      | "returnDescription"
      | "rejectDescription"
      | "reporterReturnDescription"
      | "reporterApproveDescription"
      | "processInstanceId"
      | "insuranceObject"
      | "insuranceValue"
      | "insuranceSum"
      | "franchise"
      | "reasonForPayment"
      | "calculationOfCompensation"
      | "isInsuredEvent"
      | "hasRegress"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
    >
  : V extends "_minimal"
  ? Pick<Claim, "id" | "contractNumber">
  : V extends "claim-fund-view"
  ? Pick<
      Claim,
      | "id"
      | "journalNumber"
      | "journalDate"
      | "eventTime"
      | "eventAddress"
      | "lawRepresentative"
      | "eventCase"
      | "eventExpense"
      | "status"
      | "claimFundId"
      | "euroProtocol"
      | "directSettlement"
      | "decision"
      | "reason"
      | "decisionDate"
      | "committeeDecisionFundId"
      | "payoutFundId"
      | "returnDescription"
      | "rejectDescription"
      | "reporterReturnDescription"
      | "reporterApproveDescription"
      | "processInstanceId"
      | "insuranceObject"
      | "insuranceValue"
      | "insuranceSum"
      | "franchise"
      | "reasonForPayment"
      | "calculationOfCompensation"
      | "isInsuredEvent"
      | "hasRegress"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "party"
      | "policy"
      | "eventDistrict"
      | "eventRegion"
      | "responsibleForDamage"
      | "damages"
      | "insurancePayments"
    >
  : V extends "claim-fund-view"
  ? Pick<
      Claim,
      | "id"
      | "journalNumber"
      | "journalDate"
      | "eventTime"
      | "eventAddress"
      | "lawRepresentative"
      | "eventCase"
      | "eventExpense"
      | "status"
      | "claimFundId"
      | "euroProtocol"
      | "directSettlement"
      | "decision"
      | "reason"
      | "decisionDate"
      | "committeeDecisionFundId"
      | "payoutFundId"
      | "returnDescription"
      | "rejectDescription"
      | "reporterReturnDescription"
      | "reporterApproveDescription"
      | "processInstanceId"
      | "insuranceObject"
      | "insuranceValue"
      | "insuranceSum"
      | "franchise"
      | "reasonForPayment"
      | "calculationOfCompensation"
      | "isInsuredEvent"
      | "hasRegress"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "party"
      | "policy"
      | "eventDistrict"
      | "eventRegion"
      | "responsibleForDamage"
      | "damages"
      | "insurancePayments"
    >
  : V extends "claim-online-view"
  ? Pick<
      Claim,
      | "id"
      | "journalNumber"
      | "journalDate"
      | "eventTime"
      | "eventAddress"
      | "lawRepresentative"
      | "eventCase"
      | "eventExpense"
      | "status"
      | "claimFundId"
      | "euroProtocol"
      | "directSettlement"
      | "decision"
      | "reason"
      | "decisionDate"
      | "committeeDecisionFundId"
      | "payoutFundId"
      | "returnDescription"
      | "rejectDescription"
      | "reporterReturnDescription"
      | "reporterApproveDescription"
      | "processInstanceId"
      | "insuranceObject"
      | "insuranceValue"
      | "insuranceSum"
      | "franchise"
      | "reasonForPayment"
      | "calculationOfCompensation"
      | "isInsuredEvent"
      | "hasRegress"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "policy"
      | "party"
      | "eventRegion"
      | "damages"
      | "claimRecipients"
      | "insurancePayments"
    >
  : V extends "claim-online-view"
  ? Pick<
      Claim,
      | "id"
      | "journalNumber"
      | "journalDate"
      | "eventTime"
      | "eventAddress"
      | "lawRepresentative"
      | "eventCase"
      | "eventExpense"
      | "status"
      | "claimFundId"
      | "euroProtocol"
      | "directSettlement"
      | "decision"
      | "reason"
      | "decisionDate"
      | "committeeDecisionFundId"
      | "payoutFundId"
      | "returnDescription"
      | "rejectDescription"
      | "reporterReturnDescription"
      | "reporterApproveDescription"
      | "processInstanceId"
      | "insuranceObject"
      | "insuranceValue"
      | "insuranceSum"
      | "franchise"
      | "reasonForPayment"
      | "calculationOfCompensation"
      | "isInsuredEvent"
      | "hasRegress"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "policy"
      | "party"
      | "eventRegion"
      | "damages"
      | "claimRecipients"
      | "insurancePayments"
    >
  : V extends "claim-report-view"
  ? Pick<
      Claim,
      | "id"
      | "journalNumber"
      | "journalDate"
      | "eventTime"
      | "eventAddress"
      | "lawRepresentative"
      | "eventCase"
      | "eventExpense"
      | "status"
      | "claimFundId"
      | "euroProtocol"
      | "directSettlement"
      | "decision"
      | "reason"
      | "decisionDate"
      | "committeeDecisionFundId"
      | "payoutFundId"
      | "returnDescription"
      | "rejectDescription"
      | "reporterReturnDescription"
      | "reporterApproveDescription"
      | "processInstanceId"
      | "insuranceObject"
      | "insuranceValue"
      | "insuranceSum"
      | "franchise"
      | "reasonForPayment"
      | "calculationOfCompensation"
      | "isInsuredEvent"
      | "hasRegress"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "policy"
      | "party"
      | "eventRegion"
      | "eventDistrict"
      | "damages"
      | "claimRecipients"
      | "insurancePayments"
    >
  : V extends "claim-report-view"
  ? Pick<
      Claim,
      | "id"
      | "journalNumber"
      | "journalDate"
      | "eventTime"
      | "eventAddress"
      | "lawRepresentative"
      | "eventCase"
      | "eventExpense"
      | "status"
      | "claimFundId"
      | "euroProtocol"
      | "directSettlement"
      | "decision"
      | "reason"
      | "decisionDate"
      | "committeeDecisionFundId"
      | "payoutFundId"
      | "returnDescription"
      | "rejectDescription"
      | "reporterReturnDescription"
      | "reporterApproveDescription"
      | "processInstanceId"
      | "insuranceObject"
      | "insuranceValue"
      | "insuranceSum"
      | "franchise"
      | "reasonForPayment"
      | "calculationOfCompensation"
      | "isInsuredEvent"
      | "hasRegress"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "policy"
      | "party"
      | "eventRegion"
      | "eventDistrict"
      | "damages"
      | "claimRecipients"
      | "insurancePayments"
    >
  : never;
