import { ContractExt } from "./base$ContractExt";
import { Beneficiary } from "./reference_OsgoBeneficiary";
import { OsgoPeriodType } from "../enums/enums";
import { Period } from "./reference_OsgoPeriod";
import { Vehicle } from "./osgo_Vehicle";
import { Driver } from "./osgoDriver";
import { DrivedArea } from "./reference_OsgoDrivedArea";
export class Osgo extends ContractExt {
  static NAME = "contract$Osgo";
  ownerType?: any | null;
  ownerName?: string | null;
  applicantIsOwner?: boolean | null;
  applicantIsDriver?: boolean | null;
  ownerIsDriver?: boolean | null;
  discountType?: Beneficiary | null;
  periodType?: OsgoPeriodType | null;
  period?: Period | null;
  vehicle?: Vehicle | null;
  isTaxiCar?: any | null;
  driversLimited?: boolean | null;
  driversCount?: number | null;
  drivers?: Driver[] | null;
  drivedArea?: DrivedArea | null;
  insRuleViolated?: boolean | null;
  totalAmount?: any | null;
  discountAmount?: any | null;
  tariffBase?: any | null;
  territoryCoeff?: any | null;
  limitedDriversCoeff?: any | null;
  seasonCoeff?: any | null;
  incidentCoeff?: any | null;
  ruleViolationCoeff?: any | null;
  ageCoeff?: any | null;
  experienceCoeff?: any | null;
  periodCoeff?: any | null;
  totalCoeff?: any | null;
  discountCoeff?: any | null;
  eOsgo?: boolean | null;
  eOsgoPolicySeria?: string | null;
  eOsgoPolicyNumber?: any | null;
  osgoFundId?: any | null;
}
export type OsgoViewName =
  | "_base"
  | "_local"
  | "_minimal"
  | "osgo-front-view"
  | "osgo-policy-view"
  | "osgo-view"
  | "osgoForOracleView";
export type OsgoView<V extends OsgoViewName> = V extends "_base"
  ? Pick<
      Osgo,
      | "id"
      | "contractNumber"
      | "ownerType"
      | "ownerName"
      | "applicantIsOwner"
      | "applicantIsDriver"
      | "ownerIsDriver"
      | "periodType"
      | "isTaxiCar"
      | "driversLimited"
      | "driversCount"
      | "insRuleViolated"
      | "totalAmount"
      | "discountAmount"
      | "tariffBase"
      | "territoryCoeff"
      | "limitedDriversCoeff"
      | "seasonCoeff"
      | "incidentCoeff"
      | "ruleViolationCoeff"
      | "ageCoeff"
      | "experienceCoeff"
      | "periodCoeff"
      | "totalCoeff"
      | "discountCoeff"
      | "eOsgo"
      | "eOsgoPolicySeria"
      | "eOsgoPolicyNumber"
      | "osgoFundId"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "beneficiaryType"
      | "applicationNumber"
      | "applicationDate"
      | "limitOfLiability"
      | "limitOfLiabilityCondition"
      | "damageCompensationTerm"
      | "franchiseUse"
      | "franchiseBase"
      | "franchiseType"
      | "franchiseUnit"
      | "franchise"
      | "premium"
      | "commission"
      | "paymentGraphType"
      | "distributionMethod"
      | "policyDate"
      | "duplicateCommission"
      | "terminateDate"
      | "terminatePremium"
      | "terminateCase"
      | "reissuanceDate"
      | "reissuanceType"
      | "reissuanceDifference"
      | "reissuanceSurcharge"
      | "customsSent"
      | "insuranceObject"
      | "status"
      | "serviceResponse"
      | "errorMessage"
    >
  : V extends "_local"
  ? Pick<
      Osgo,
      | "id"
      | "ownerType"
      | "ownerName"
      | "applicantIsOwner"
      | "applicantIsDriver"
      | "ownerIsDriver"
      | "periodType"
      | "isTaxiCar"
      | "driversLimited"
      | "driversCount"
      | "insRuleViolated"
      | "totalAmount"
      | "discountAmount"
      | "tariffBase"
      | "territoryCoeff"
      | "limitedDriversCoeff"
      | "seasonCoeff"
      | "incidentCoeff"
      | "ruleViolationCoeff"
      | "ageCoeff"
      | "experienceCoeff"
      | "periodCoeff"
      | "totalCoeff"
      | "discountCoeff"
      | "eOsgo"
      | "eOsgoPolicySeria"
      | "eOsgoPolicyNumber"
      | "osgoFundId"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "beneficiaryType"
      | "applicationNumber"
      | "applicationDate"
      | "limitOfLiability"
      | "limitOfLiabilityCondition"
      | "damageCompensationTerm"
      | "franchiseUse"
      | "franchiseBase"
      | "franchiseType"
      | "franchiseUnit"
      | "franchise"
      | "premium"
      | "commission"
      | "paymentGraphType"
      | "distributionMethod"
      | "policyDate"
      | "duplicateCommission"
      | "terminateDate"
      | "terminatePremium"
      | "terminateCase"
      | "reissuanceDate"
      | "reissuanceType"
      | "reissuanceDifference"
      | "reissuanceSurcharge"
      | "customsSent"
      | "insuranceObject"
      | "status"
      | "serviceResponse"
      | "errorMessage"
    >
  : V extends "_minimal"
  ? Pick<Osgo, "id" | "contractNumber">
  : V extends "osgo-front-view"
  ? Pick<
      Osgo,
      | "id"
      | "contractNumber"
      | "discountType"
      | "period"
      | "vehicle"
      | "periodType"
      | "ownerName"
      | "ownerType"
      | "driversLimited"
      | "drivers"
      | "drivedArea"
      | "totalAmount"
      | "discountAmount"
      | "partyType"
      | "contractStartDate"
      | "contractEndDate"
      | "premium"
      | "policyDate"
      | "party"
      | "applicantIsOwner"
      | "applicantIsDriver"
      | "beneficiary"
      | "driversCount"
      | "status"
      | "eOsgoPolicySeria"
      | "eOsgoPolicyNumber"
      | "isTaxiCar"
    >
  : V extends "osgo-policy-view"
  ? Pick<Osgo, "id" | "contractNumber" | "policy">
  : V extends "osgo-view"
  ? Pick<
      Osgo,
      | "id"
      | "ownerType"
      | "ownerName"
      | "applicantIsOwner"
      | "applicantIsDriver"
      | "ownerIsDriver"
      | "periodType"
      | "isTaxiCar"
      | "driversLimited"
      | "driversCount"
      | "insRuleViolated"
      | "totalAmount"
      | "discountAmount"
      | "tariffBase"
      | "territoryCoeff"
      | "limitedDriversCoeff"
      | "seasonCoeff"
      | "incidentCoeff"
      | "ruleViolationCoeff"
      | "ageCoeff"
      | "experienceCoeff"
      | "periodCoeff"
      | "totalCoeff"
      | "discountCoeff"
      | "eOsgo"
      | "eOsgoPolicySeria"
      | "eOsgoPolicyNumber"
      | "osgoFundId"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "beneficiaryType"
      | "applicationNumber"
      | "applicationDate"
      | "limitOfLiability"
      | "limitOfLiabilityCondition"
      | "damageCompensationTerm"
      | "franchiseUse"
      | "franchiseBase"
      | "franchiseType"
      | "franchiseUnit"
      | "franchise"
      | "premium"
      | "commission"
      | "paymentGraphType"
      | "distributionMethod"
      | "policyDate"
      | "duplicateCommission"
      | "terminateDate"
      | "terminatePremium"
      | "terminateCase"
      | "reissuanceDate"
      | "reissuanceType"
      | "reissuanceDifference"
      | "reissuanceSurcharge"
      | "customsSent"
      | "insuranceObject"
      | "status"
      | "serviceResponse"
      | "errorMessage"
      | "period"
      | "vehicle"
      | "drivers"
      | "drivedArea"
      | "productGroup"
      | "productSubGroup"
      | "product"
      | "party"
      | "discountType"
      | "beneficiary"
      | "organization"
      | "insuranceObjects"
    >
  : V extends "osgoForOracleView"
  ? Pick<
      Osgo,
      | "id"
      | "contractNumber"
      | "applicationNumber"
      | "applicationDate"
      | "contractNumber"
      | "contractStartDate"
      | "contractEndDate"
      | "premium"
      | "eOsgoPolicySeria"
      | "eOsgoPolicyNumber"
      | "partyType"
      | "party"
    >
  : never;
