import { ContractExt } from "./base$ContractExt";
import { OsgopPeriod } from "./OsgopPeriod";
import { Vehicle } from "./osgo_Vehicle";
export class Osgop extends ContractExt {
  static NAME = "osgop_Osgop";
  osgopPeriod?: OsgopPeriod | null;
  days?: number | null;
  ratio?: any | null;
  vehicle?: Vehicle | null;
}
export type OsgopViewName =
  | "_base"
  | "_local"
  | "_minimal"
  | "osgop-fund-view"
  | "osgop-vehicle-view"
  | "osgop-view";
export type OsgopView<V extends OsgopViewName> = V extends "_base"
  ? Pick<
      Osgop,
      | "id"
      | "contractNumber"
      | "days"
      | "ratio"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "isVillage"
      | "beneficiaryType"
      | "applicationNumber"
      | "applicationDate"
      | "limitOfLiability"
      | "limitOfLiabilityForLiability"
      | "limitOfLiabilityCondition"
      | "damageCompensationTerm"
      | "franchiseUse"
      | "franchiseBase"
      | "franchiseType"
      | "franchiseUnit"
      | "franchise"
      | "premium"
      | "commission"
      | "paymentGraphType"
      | "distributionMethod"
      | "policyDate"
      | "duplicateCommission"
      | "terminateDate"
      | "terminatePremium"
      | "terminateCase"
      | "reissuanceDate"
      | "reissuanceType"
      | "reissuanceDifference"
      | "reissuanceSurcharge"
      | "customsSent"
      | "insuranceObject"
      | "status"
      | "serviceResponse"
      | "errorMessage"
      | "online"
      | "fundUUID"
      | "eContract"
      | "eContractPolicySeria"
      | "eContractPolicyNumber"
      | "contractFundId"
    >
  : V extends "_local"
  ? Pick<
      Osgop,
      | "id"
      | "days"
      | "ratio"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "isVillage"
      | "beneficiaryType"
      | "applicationNumber"
      | "applicationDate"
      | "limitOfLiability"
      | "limitOfLiabilityForLiability"
      | "limitOfLiabilityCondition"
      | "damageCompensationTerm"
      | "franchiseUse"
      | "franchiseBase"
      | "franchiseType"
      | "franchiseUnit"
      | "franchise"
      | "premium"
      | "commission"
      | "paymentGraphType"
      | "distributionMethod"
      | "policyDate"
      | "duplicateCommission"
      | "terminateDate"
      | "terminatePremium"
      | "terminateCase"
      | "reissuanceDate"
      | "reissuanceType"
      | "reissuanceDifference"
      | "reissuanceSurcharge"
      | "customsSent"
      | "insuranceObject"
      | "status"
      | "serviceResponse"
      | "errorMessage"
      | "online"
      | "fundUUID"
      | "eContract"
      | "eContractPolicySeria"
      | "eContractPolicyNumber"
      | "contractFundId"
    >
  : V extends "_minimal"
  ? Pick<Osgop, "id" | "contractNumber">
  : V extends "osgop-fund-view"
  ? Pick<
      Osgop,
      | "id"
      | "days"
      | "ratio"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "isVillage"
      | "beneficiaryType"
      | "applicationNumber"
      | "applicationDate"
      | "limitOfLiability"
      | "limitOfLiabilityForLiability"
      | "limitOfLiabilityCondition"
      | "damageCompensationTerm"
      | "franchiseUse"
      | "franchiseBase"
      | "franchiseType"
      | "franchiseUnit"
      | "franchise"
      | "premium"
      | "commission"
      | "paymentGraphType"
      | "distributionMethod"
      | "policyDate"
      | "duplicateCommission"
      | "terminateDate"
      | "terminatePremium"
      | "terminateCase"
      | "reissuanceDate"
      | "reissuanceType"
      | "reissuanceDifference"
      | "reissuanceSurcharge"
      | "customsSent"
      | "insuranceObject"
      | "status"
      | "serviceResponse"
      | "errorMessage"
      | "online"
      | "fundUUID"
      | "eContract"
      | "eContractPolicySeria"
      | "eContractPolicyNumber"
      | "contractFundId"
      | "party"
      | "organization"
      | "policy"
      | "policies"
      | "product"
      | "entriesJournalDt"
      | "entriesJournalKt"
    >
  : V extends "osgop-vehicle-view"
  ? Pick<Osgop, "id" | "contractNumber" | "vehicle">
  : V extends "osgop-view"
  ? Pick<
      Osgop,
      | "id"
      | "days"
      | "ratio"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "isVillage"
      | "beneficiaryType"
      | "applicationNumber"
      | "applicationDate"
      | "limitOfLiability"
      | "limitOfLiabilityForLiability"
      | "limitOfLiabilityCondition"
      | "damageCompensationTerm"
      | "franchiseUse"
      | "franchiseBase"
      | "franchiseType"
      | "franchiseUnit"
      | "franchise"
      | "premium"
      | "commission"
      | "paymentGraphType"
      | "distributionMethod"
      | "policyDate"
      | "duplicateCommission"
      | "terminateDate"
      | "terminatePremium"
      | "terminateCase"
      | "reissuanceDate"
      | "reissuanceType"
      | "reissuanceDifference"
      | "reissuanceSurcharge"
      | "customsSent"
      | "insuranceObject"
      | "status"
      | "serviceResponse"
      | "errorMessage"
      | "online"
      | "fundUUID"
      | "eContract"
      | "eContractPolicySeria"
      | "eContractPolicyNumber"
      | "contractFundId"
      | "productGroup"
      | "productSubGroup"
      | "product"
      | "party"
      | "beneficiary"
      | "organization"
      | "currencyPremium"
      | "currencyLiability"
      | "currencyContract"
      | "vehicle"
      | "osgopPeriod"
    >
  : never;
