import { ContractExt } from "./base$ContractExt";
import { ActivityCoefficient } from "./reference_OsgorActivityCoefficient";
export class Osgor extends ContractExt {
  static NAME = "osgor_Osgor";
  days?: number | null;
  ratio?: any | null;
  activityCoefficient?: ActivityCoefficient | null;
}
export type OsgorViewName = "_base" | "_local" | "_minimal";
export type OsgorView<V extends OsgorViewName> = V extends "_base"
  ? Pick<
      Osgor,
      | "id"
      | "contractNumber"
      | "days"
      | "ratio"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "beneficiaryType"
      | "applicationNumber"
      | "applicationDate"
      | "limitOfLiability"
      | "limitOfLiabilityCondition"
      | "damageCompensationTerm"
      | "franchiseUse"
      | "franchiseBase"
      | "franchiseType"
      | "franchiseUnit"
      | "franchise"
      | "premium"
      | "commission"
      | "paymentGraphType"
      | "distributionMethod"
      | "policyDate"
      | "duplicateCommission"
      | "terminateDate"
      | "terminatePremium"
      | "terminateCase"
      | "reissuanceDate"
      | "reissuanceType"
      | "reissuanceDifference"
      | "reissuanceSurcharge"
      | "customsSent"
      | "insuranceObject"
      | "status"
      | "serviceResponse"
      | "errorMessage"
    >
  : V extends "_local"
  ? Pick<
      Osgor,
      | "id"
      | "days"
      | "ratio"
      | "legacyId"
      | "fundId"
      | "startDate"
      | "endDate"
      | "writeHistory"
      | "partyType"
      | "contractNumber"
      | "contractDate"
      | "contractStartDate"
      | "contractEndDate"
      | "description"
      | "fixDate"
      | "beneficiaryType"
      | "applicationNumber"
      | "applicationDate"
      | "limitOfLiability"
      | "limitOfLiabilityCondition"
      | "damageCompensationTerm"
      | "franchiseUse"
      | "franchiseBase"
      | "franchiseType"
      | "franchiseUnit"
      | "franchise"
      | "premium"
      | "commission"
      | "paymentGraphType"
      | "distributionMethod"
      | "policyDate"
      | "duplicateCommission"
      | "terminateDate"
      | "terminatePremium"
      | "terminateCase"
      | "reissuanceDate"
      | "reissuanceType"
      | "reissuanceDifference"
      | "reissuanceSurcharge"
      | "customsSent"
      | "insuranceObject"
      | "status"
      | "serviceResponse"
      | "errorMessage"
    >
  : V extends "_minimal"
  ? Pick<Osgor, "id" | "contractNumber">
  : never;
