// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/3/2025, 8:01:32 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/plugins/**/*.{js,ts,mjs}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/composables/**/*.{js,ts,mjs}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/utils/**/*.{js,ts,mjs}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/app.config.{js,ts,mjs}","/Users/farrukhmirisoyev/Myprojects/tysminiapp/telegram-miniapp/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;