// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/27/2025, 12:34:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/My projects/miniapp_z/telegram-miniapp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/My projects/miniapp_z/telegram-miniapp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/My projects/miniapp_z/telegram-miniapp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/My projects/miniapp_z/telegram-miniapp/plugins/**/*.{js,ts,mjs}","C:/My projects/miniapp_z/telegram-miniapp/composables/**/*.{js,ts,mjs}","C:/My projects/miniapp_z/telegram-miniapp/utils/**/*.{js,ts,mjs}","C:/My projects/miniapp_z/telegram-miniapp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/My projects/miniapp_z/telegram-miniapp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/My projects/miniapp_z/telegram-miniapp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/My projects/miniapp_z/telegram-miniapp/app.config.{js,ts,mjs}","C:/My projects/miniapp_z/telegram-miniapp/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;